i_author = 'Connor Hess'
i_copyright = 'Copyright (C) 2020, Connor Hess'
i_credits = ['Connor Hess']
i_license = 'The MIT License (MIT)'
i_version = (0.9)
i_maintainer = 'Connor Hess'
i_email = 'hessconnor41@gmail.com'
i_status = 'Alpha'
i_AppName_ = 'EasyPOS'
